apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mktxp.fullname" . }}
  labels:
    {{- include "mktxp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "mktxp.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics